### ISSUE TITLE
Document container affinity in the installation guide and the rpc_user_config.yml file

### ISSUE THREAD

**Issue by klevenstein** [rpcdocs/docs-issues#22]
See https://bugs.launchpad.net/openstack-ansible/+bug/1413262
> Document container affinity in the installation guide and the rpc_user_config.yml file. For example, to deploy three RabbitMQ and Galera containers on the same infra host:

```
infra_hosts:  
  infra1:  
    ip: 192.168.1.11  
    affinity:  
      rabbitmq_container: 3  
      galera_container: 3  
```
